export let categoryList = [
    { title: "Main Course", value: "Main Course" },
    { title: "Fast Food", value: "Fast Food" },
    { title: "Thali", value: "Thali" },
    { title: "Chinese", value: "Chinese" },
    { title: "North Indian", value: "North Indian" },
    { title: "South Indian", value: "South Indian" },
    { title: "Maharashtrian", value: "Maharashtrian" },
    { title: "Breakfast", value: "Breakfast" },
    { title: "Snacks", value: "Snacks" },
    { title: "Juice and Shakes", value: "Juice and Shakes" },
    { title: "Roti and Parantha", value: "Roti and Parantha" },
    { title: "Tea and Beverage", value: "Tea and Beverage" },
    { title: "Sandwich and Breads", value: "Sandwich and Breads" },
    { title: "Chaat", value: "Chaat" },
    { title: "Maggi", value: "Maggi" },
    { title: "Egg and Omelette", value: "Egg and Omelette" },
    { title: "Combos", value: "Combos" },
    { title: "Sweet", value: "Sweet" },
    { title: "Desserts", value: "Desserts" },
    { title: "Biryani and Rice", value: "Biryani and Rice" },
    { title: "Daily", value: "Daily" },
    { title: "Add On", value: "Add on" },
    { title: "MRP", value: "MRP" },
];