export const routeMapper = {
    home:'Home',
    login:'Login',
    dashboard:'Dashboard',
    foodItem:'Food Item',
    specialItem:'Special Item',
    mealPackage:'Meal Package',
    searchKitchen:'Search Kitchen',
    addKitchen:'Add Kitchen',
    kitchenLeads:'Kitchen Leads',
    testNotification:'Test Notification',
    searchUser:'Search User',
    couponUser:'Coupon User',
    currentOrder:'Current Order',
    refundOrder:'Refund Order',
    searchOrder:'Search Order',
    manualOrder:'Manual Order',
    bulkOrder:'Bulk Order',
    mealEndDetail:'Meal End Details',
    geofencing:'GeoFencing',
    addgeofencing:'Add GeoFencing',
    faq:'FAQ',
    configVariables:'Config Variables',
    configImages:'Config Images',
    appVersionControl:'App Version Control',
    offercoupon:'Offer Coupon',
    offervoucher:'Offer Voucher',
    banner:'Banner',
    serverlogs:'Server Logs',
    appFeedback:'App Feedback',
    dishSuggestion:'Dish Suggestion',
    admin:'Admin',
    adminAdd:'Add Admin',
    policy:'Policy',
    addPolicy:'Add Policy'
}