import { environment } from './../../environments/environment';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MlApiConfigService {
  private baseUrl: string = environment.mlServerUrl;
  apiEndPointObj: any;
  constructor() {
    this.init();
  }
  private init() {
    this.apiEndPointObj = {      
      loginAdmin: {url: `${this.baseUrl}/authadmin/loginAdmin`, method: 'POST'},
      verifyOTP: {url: `${this.baseUrl}/authadmin/verifyOTP`, method: 'POST'},
      logout: {url: `${this.baseUrl}/authadmin/logout`, method: 'GET'},
      getAllFooditems: {url: `${this.baseUrl}/api/getAllFooditems`, method: 'GET'},
      getfoodItemsList: {url: `${this.baseUrl}/api/fooditemlist`, method: 'GET'},
      saveFoodItem: {url: `${this.baseUrl}/api/fooditem`, method: 'POST'},
      updateFoodItem: {url: `${this.baseUrl}/api/updatefoodItem`, method: 'POST'},
      deleteFooditem: {url: `${this.baseUrl}/api/deleteFooditem`, method: 'POST'},
      getaddonlist:  {url: `${this.baseUrl}/api/getaddonlist`, method: 'GET'},
      deleteAddon: {url: `${this.baseUrl}/api/deleteAddon`, method: 'DELETE'},
      saveaddon: {url: `${this.baseUrl}/api/saveaddon`, method: 'POST'},
      updateaddon: {url: `${this.baseUrl}/api/updateaddon`, method: 'POST'},
      savekitchenPartner: {url: `${this.baseUrl}/api/kitchenPartner`, method: 'POST'},
      searchKitchenWithFilter: {url: `${this.baseUrl}/api/searchKitchenWithFilter`, method: 'POST'},
      exportKitchenPartners: {url: `${this.baseUrl}/api/exportKitchenPartners`, method: 'POST'},
      updateKitchenPatner: {url: `${this.baseUrl}/api/updateKitchenPatner`, method: 'POST'},
      getKitchenItemList: {url: `${this.baseUrl}/api/getKitchenItemList`, method: 'GET'},
      getKitchenAddonList: {url: `${this.baseUrl}/api/getKitchenAddonList`, method: 'GET'},
      saveKitchenMenu: {url: `${this.baseUrl}/api/saveKitchenMenu`, method: 'POST'},
      getAllGeoFencingList: {url: `${this.baseUrl}/api/getAllGeoFencingList`, method: 'GET'},
      getGeoFencingList: {url: `${this.baseUrl}/api/getGeoFencingList`, method: 'GET'},
      saveGeoFencing: {url: `${this.baseUrl}/api/saveGeoFencing`, method: 'POST'},
      updateGeoFencing: {url: `${this.baseUrl}/api/updateGeoFencing`, method: 'POST'},
      deleteGeoFencing: {url: `${this.baseUrl}/api/deleteGeoFencing`, method: 'DELETE'},
      getKitchenWallet: {url: `${this.baseUrl}/api/getKitchenWallet`, method: 'GET'},
      userRewardsPointsHistory: {url: `${this.baseUrl}/api/userRewardsPointsHistory`, method: 'GET'},
      saveKitchenWallet: {url: `${this.baseUrl}/api/saveKitchenWallet`, method: 'POST'},
      updateKitchenWallet: {url: `${this.baseUrl}/api/updateKitchenWallet`, method: 'POST'},
      getAllVariables: {url: `${this.baseUrl}/api/getAllVariables`, method: 'GET'},
      saveVariable: {url: `${this.baseUrl}/api/saveVariable`, method: 'POST'},
      updateVariable: {url: `${this.baseUrl}/api/updateVariable`, method: 'POST'},
      deleteVariable: {url: `${this.baseUrl}/api/deleteVariable`, method: 'DELETE'},
      getAllFAQs: {url: `${this.baseUrl}/api/getAllFAQs`, method: 'GET'},
      saveFAQ: {url: `${this.baseUrl}/api/saveFAQ`, method: 'POST'},
      updateFAQ: {url: `${this.baseUrl}/api/updateFAQ`, method: 'POST'},
      deleteFAQ: {url: `${this.baseUrl}/api/deleteFAQ`, method: 'DELETE'},
      searchFoodOrderList: {url: `${this.baseUrl}/api/searchFoodOrderList`, method: 'POST'},
      checkCancelEligibility: {url: `${this.baseUrl}/api/checkCancelEligibility`, method: 'GET'},
      refund: {url: `${this.baseUrl}/transaction/refund`, method: 'POST'},
      updateOrderStatus: {url: `${this.baseUrl}/api/updateOrderStatus`, method: 'POST'},
      getVariables: {url: `${this.baseUrl}/api/getVariables`, method: 'POST'},
      adminProfile: {url: `${this.baseUrl}/api/adminProfile`, method: 'POST'},
      getAdminProfileList: {url: `${this.baseUrl}/api/getAdminProfileList`, method: 'GET'},
      getadminprofile: {url: `${this.baseUrl}/api/getadminprofile`, method: 'GET'},
      updateadminprofile: {url: `${this.baseUrl}/api/updateadminprofile`, method: 'POST'},
      searchAdmin: {url: `${this.baseUrl}/api/searchAdmin`, method: 'POST'},
      deleteAdmin: {url: `${this.baseUrl}/api/deleteAdmin`, method: 'DELETE'},
      getdashboardCount: {url: `${this.baseUrl}/api/getdashboardCount`, method: 'GET'},
      getKitchenPatnerCount: {url: `${this.baseUrl}/api/getKitchenPatnerCount`, method: 'GET'},
      getUserCount: {url: `${this.baseUrl}/api/getUserCount`, method: 'GET'},
      getkitchenlead: {url: `${this.baseUrl}/api/getkitchenlead`, method: 'GET'},
      getListForReward: {url: `${this.baseUrl}/api/getListForReward`, method: 'POST'},
      updateProfileApproval: {url: `${this.baseUrl}/api/updateProfileApproval`, method: 'POST'},
      getAllAppVersionList: {url: `${this.baseUrl}/api/getAllAppVersionList`, method: 'GET'},
      saveAppVersion: {url: `${this.baseUrl}/api/saveAppVersion`, method: 'POST'},
      updateAppVersion: {url: `${this.baseUrl}/api/updateAppVersion`, method: 'POST'},
      getOfferCouponList: {url: `${this.baseUrl}/api/getOfferCouponList`, method: 'GET'},
      saveOfferCoupon: {url: `${this.baseUrl}/api/saveOfferCoupon`, method: 'POST'},
      updateOfferCoupon: {url: `${this.baseUrl}/api/updateOfferCoupon`, method: 'POST'},
      deleteOfferCoupon: {url: `${this.baseUrl}/api/deleteOfferCoupon`, method: 'DELETE'},
      getAllBanners: {url: `${this.baseUrl}/api/bannerlist`, method: 'GET'},
      saveBanner: {url: `${this.baseUrl}/api/banner`, method: 'POST'},
      updateBanner: {url: `${this.baseUrl}/api/updatebanner`, method: 'POST'},
      deleteBanner: {url: `${this.baseUrl}/api/deletebanner`, method: 'DELETE'},
      updateDiscountOffer: {url: `${this.baseUrl}/api/updateDiscountOffer`, method: 'POST'},
      getGeneralAppFeeback: {url: `${this.baseUrl}/api/getGeneralAppFeeback`, method: 'GET'},
      createKitchenTestUser: {url: `${this.baseUrl}/test/createKitchenTestUser`, method: 'POST'},
      validateKitchenPartner: {url: `${this.baseUrl}/api/validateKitchenPartner`, method: 'POST'},
      leadnoteligible: {url: `${this.baseUrl}/api/leadnoteligible`, method: 'POST'},
      getDishList: {url: `${this.baseUrl}/api/getDishList`, method: 'GET'},
      dishacknowledge: {url: `${this.baseUrl}/api/dishacknowledge`, method: 'PUT'},
      feedbackacknowledge: {url: `${this.baseUrl}/api/feedbackacknowledge`, method: 'PUT'},
      updatekitchenleadstatus: {url: `${this.baseUrl}/api/updatekitchenleadstatus`, method: 'PUT'},
      getAllConfigImages: {url: `${this.baseUrl}/api/getAllConfigImages`, method: 'GET'},
      saveConfigImage: {url: `${this.baseUrl}/api/saveConfigImage`, method: 'POST'},
      updateConfigImage: {url: `${this.baseUrl}/api/updateConfigImage`, method: 'POST'},
      validateKitchenReferralCode: {url: `${this.baseUrl}/api/validateKitchenReferralCode`, method: 'GET'},
      payAmtToKitchen : {url: `${this.baseUrl}/api/payAmtToKitchen`, method: 'POST'},
      payServerFoodOrderAmtToKitchenDirect : {url: `${this.baseUrl}/api/payServerFoodOrderAmtToKitchenDirect`, method: 'POST'},
      payServerFoodOrderAmtToKitchen : {url: `${this.baseUrl}/api/payServerFoodOrderAmtToKitchen`, method: 'POST'},
      kitchenOpenedStatus : {url: `${this.baseUrl}/api/kitchenOpenedStatus`, method: 'PUT'},
      getCurrentOrdersCount: {url: `${this.baseUrl}/api/getCurrentOrdersCount`, method: 'GET'},
      getCurrentOrdersList: {url: `${this.baseUrl}/api/getCurrentOrdersList`, method: 'GET'},
      trackDeliveryTask: {url: `${this.baseUrl}/api/trackdeliveryTask`, method: 'GET'},
      serverlogs: {url: `${this.baseUrl}/public/serverlogs`, method: 'GET'},
      searchUserWithFilter: {url: `${this.baseUrl}/api/searchUserWithFilter`, method: 'POST'},
      getClusterKitchenPartnerList:  {url: `${this.baseUrl}/api/getClusterKitchenPartnerList`, method: 'POST'},
      getCustomerProfileList: {url: `${this.baseUrl}/api/getCustomerProfileList`, method: 'GET'},
      updateFoodOrder:  {url: `${this.baseUrl}/api/updateFoodOrder`, method: 'POST'},
      createDeliveryTask: {url: `${this.baseUrl}/api/createDunzoTask`, method: 'POST'},
      createOnlyDunzoTask: {url: `${this.baseUrl}/api/createOnlyDunzoTask`, method: 'POST'},
      getKitchenPartner: {url: `${this.baseUrl}/api/getKitchenPartner`, method: 'GET'},
      sendTestNotification: {url: `${this.baseUrl}/api/sendTestNotification`, method: 'POST'},
      getKitchenPartnerProfile: {url: `${this.baseUrl}/api/getKitchenPartnerProfile`, method: 'GET'},
      performOrderTransfer: {url: `${this.baseUrl}/api/performOrderTransfer`, method: 'POST'},
      performBulkOrderTransfer: {url: `${this.baseUrl}/api/performBulkOrderTransfer`, method: 'POST'},
      performSubscriptionOrderTransfer: {url: `${this.baseUrl}/api/performSubscriptionOrderTransfer`, method: 'POST'},
      getGatewayPaymentHistory: {url: `${this.baseUrl}/transaction/getGatewayPaymentHistory`, method: 'GET'},
      refundGatewayPayment: {url: `${this.baseUrl}/transaction/refundGatewayPayment`, method: 'POST'},
      validatePaytmPaymentTransaction: {url: `${this.baseUrl}/transaction/validatePaytmPaymentTransaction`, method: 'POST'},
      getRefundOrders: {url: `${this.baseUrl}/api/getRefundOrders`, method: 'GET'},
      updateComplianceByAdmin: {url: `${this.baseUrl}/api/updateComplianceByAdmin`, method: 'POST'},
      getCurrentSubscriptionCount: {url: `${this.baseUrl}/api/getCurrentSubscriptionCount`, method: 'GET'},
      getCurrentSubOrdersList: {url: `${this.baseUrl}/api/getCurrentSubOrdersList`, method: 'GET'},
      updateSubscriptionDetails: {url: `${this.baseUrl}/api/updateSubscriptionDetails`, method: 'POST'},
      getFoodOrder: {url: `${this.baseUrl}/api/getFoodOrder`, method: 'GET'},
      acceptSubscriptionOrder: {url: `${this.baseUrl}/api/acceptSubscriptionOrder`, method: 'POST'},
      updateSubscriptionFoodOrder: {url: `${this.baseUrl}/api/updateSubscriptionFoodOrder`, method: 'POST'},
      getSubscriptionRefundOrders: {url: `${this.baseUrl}/api/getSubscriptionRefundOrders`, method: 'GET'},
      searchSubscriptionFoodOrderList: {url: `${this.baseUrl}/api/searchSubscriptionFoodOrderList`, method: 'POST'},
      searchPackageFoodOrderList: {url: `${this.baseUrl}/api/searchPackageFoodOrderList`, method: 'POST'},
      resechedulePackageOrder: {url: `${this.baseUrl}/api/resechedulePackageOrder`, method: 'GET'},
      changeMealTypeFromAdmin: {url: `${this.baseUrl}/api/changeMealTypeFromAdmin`, method: 'POST'},
      getOrderPackage: {url: `${this.baseUrl}/api/getOrderPackage`, method: 'GET'},
      getOfferVoucherList: {url: `${this.baseUrl}/api/getOfferVoucherList`, method: 'GET'},
      saveOfferVoucher: {url: `${this.baseUrl}/api/saveOfferVoucher`, method: 'POST'},
      updateOfferVoucher: {url: `${this.baseUrl}/api/updateOfferVoucher`, method: 'POST'},
      deleteOfferVoucher: {url: `${this.baseUrl}/api/deleteOfferVoucher`, method: 'DELETE'},
      refundToUserWallet: {url: `${this.baseUrl}/transaction/refundToUserWallet`, method: 'PUT'},
      updateCouponList: {url: `${this.baseUrl}/api/updateCouponList`, method: 'PUT'},
      getSpecialItems: {url: `${this.baseUrl}/api/getSpecialItems`, method: 'GET'},
      searchOrderBookingList: {url: `${this.baseUrl}/api/searchOrderBookingList`, method: 'POST'},
      getCustomerProfileByMobile: {url: `${this.baseUrl}/api/getCustomerProfileByMobile`, method: 'GET'},
      getKitchenbyMobile: {url: `${this.baseUrl}/api/getKitchenbyMobile`, method: 'GET'},
      updateOrderBooking: {url: `${this.baseUrl}/api/updateOrderBooking`, method: 'POST'},
      saveOrderBooking: {url: `${this.baseUrl}/api/saveOrderBooking`, method: 'POST'},
      createFoodOrderByAdmin: {url: `${this.baseUrl}/transaction/createFoodOrderByAdmin`, method: 'POST'},
      getNearestKitchen: {url: `${this.baseUrl}/api/getNearestKitchen`, method: 'POST'},
      getNearestKitchensOfType: {url: `${this.baseUrl}/api/getNearestKitchensOfType`, method: 'POST'},
      createPorterTask: {url: `${this.baseUrl}/api/createPorterTask`, method: 'POST'},
      updateManualDelivery: {url: `${this.baseUrl}/api/updateManualDelivery`, method: 'PUT'},
      deliveryByMealaweBoy: {url: `${this.baseUrl}/api/deliveryByMealaweBoy`, method: 'PUT'},
      updateBulkManualDelivery: {url: `${this.baseUrl}/api/updateBulkManualDelivery`, method: 'PUT'},
      trackPorterDeliveryTask: {url: `${this.baseUrl}/api/trackPorterTask`, method: 'GET'},
      cancelPorterTask: {url: `${this.baseUrl}/api/cancelPorterTask`, method: 'PUT'},
      cancelDunzotask: {url: `${this.baseUrl}/api/cancelDunzotask`, method: 'PUT'},
      getdeliveryAmount: {url: `${this.baseUrl}/api/quote`, method: 'POST'},
      getOneConfigImage: {url: `${this.baseUrl}/api/getOneConfigImage`, method: 'GET'},
      withdrawalHistory: {url: `${this.baseUrl}/api/withdrawalHistory`, method: 'GET'},
      getCustomerPastOrders: {url: `${this.baseUrl}/api/getCustomerPastOrders`, method: 'GET'},
      getCustomerPackageList: {url: `${this.baseUrl}/api/getCustomerPackageList`, method: 'GET'},
      getCustomerBulkOrderList: {url: `${this.baseUrl}/api/getCustomerBulkOrderList`, method: 'GET'},
      getCashbackListUser: {url: `${this.baseUrl}/api/getCashbackListUser`, method: 'GET'},
      saveCashback: {url: `${this.baseUrl}/api/saveCashback`, method: 'POST'},
      getCustomerWalletBalance: {url: `${this.baseUrl}/api/getWalletBalance`, method: 'GET'},
      depositeInWallet: {url: `${this.baseUrl}/api/depositeInWallet`, method: 'POST'},
      withdrawFromWallet: {url: `${this.baseUrl}/api/withdrawFromWallet`, method: 'POST'},
      placePaymentFailedOrder: {url: `${this.baseUrl}/transaction/placePaymentFailedOrder`, method: 'POST'},
      searchBulkOrderList: {url: `${this.baseUrl}/api/searchBulkOrderList`, method: 'POST'},
      updateBulkOrderStatus: {url: `${this.baseUrl}/api/updateBulkOrderStatus`, method: 'POST'},
      getCurrentBulkOrdersList: {url: `${this.baseUrl}/api/getCurrentBulkOrdersList`, method: 'GET'},
      createImage: {url: `${this.baseUrl}/images/createImage`, method: 'POST'},
      getCurrentPackageOrdersList: {url: `${this.baseUrl}/api/getCurrentPackageOrdersList`, method: 'GET'},
      getCurrentPackageCount: {url: `${this.baseUrl}/api/getCurrentPackageCount`, method: 'GET'},
      updatePackageFoodOrder: {url: `${this.baseUrl}/api/updatePackageFoodOrder`, method: 'POST'},
      
      createDailyPackageOrder: {url: `${this.baseUrl}/api/createDailyPackageOrder`, method: 'POST'},
      performPackageOrderTransfer: {url: `${this.baseUrl}/api/performPackageOrderTransfer`, method: 'POST'},
      getMealPackageList: {url: `${this.baseUrl}/api/getMealPackageList`, method: 'GET'},
      saveMealPackage: {url: `${this.baseUrl}/api/saveMealPackage`, method: 'POST'},
      updateMealPackage: {url: `${this.baseUrl}/api/updateMealPackage`, method: 'POST'},
      deleteMealPackage: {url: `${this.baseUrl}/api/deleteMealPackage`, method: 'DELETE'},
      activateGeoFencing : {url: `${this.baseUrl}/api/activateGeoFencing`, method: 'PUT'},
      getSubscriptionEndDetails: {url: `${this.baseUrl}/api/getSubscriptionEndDetails`, method: 'GET'},
      getOrderPackageByOrderNo: {url: `${this.baseUrl}/api/getOrderPackageByOrderNo`, method: 'GET'},
      getKitchenPastPackageOrders: {url: `${this.baseUrl}/api/getKitchenPastPackageOrders`, method: 'GET'},
      addPolicy: {url: `${this.baseUrl}/api/addPolicy`, method: 'POST'},
      getAllPolicy: {url: `${this.baseUrl}/api/getAllPolicy`, method: 'GET'},
      updatePolicy: {url: `${this.baseUrl}/api/updatePolicy`, method: 'POST'},
      deletePolicy: {url: `${this.baseUrl}/api/deletePolicy`, method: 'DELETE'},
      exportFoodOrderList: {url: `${this.baseUrl}/api/exportFoodOrderList`, method: 'POST'},
      exportFoodOrderPackageList: {url: `${this.baseUrl}/api/exportFoodOrderPackageList`, method: 'POST'},
      getKitchenAssignedOrders: {url: `${this.baseUrl}/api/getKitchenAssignedOrders`, method: 'POST'},
      deductkitchenWallet: {url: `${this.baseUrl}/api/deductkitchenWallet`, method: 'POST'},
      addkitchenWallet: {url: `${this.baseUrl}/api/addkitchenWallet`, method: 'POST'},
      exportCustomerList: {url: `${this.baseUrl}/api/exportCustomerList`, method: 'POST'},
      createShadowFaxTask: {url: `${this.baseUrl}/api/createShadowFaxTask`, method: 'POST'},
      cancelShadowFaxTask: {url: `${this.baseUrl}/api/cancelShadowFaxTask`, method: 'PUT'},
      saveBulkFoodItem: {url: `${this.baseUrl}/api/saveBulkFoodItem`, method: 'POST'},
      updateBulkfoodItem: {url: `${this.baseUrl}/api/updateBulkfoodItem`, method: 'POST'},
      getAllBulkFooditems: {url: `${this.baseUrl}/api/getAllBulkFooditems`, method: 'GET'},
      deleteBulkFoodItem: {url: `${this.baseUrl}/api/deleteBulkFoodItem`, method: 'POST'},
      fetchBulkMenu: {url: `${this.baseUrl}/api/fetchBulkMenu`, method: 'GET'},
      bulkMenuAdd: {url: `${this.baseUrl}/api/bulkMenuAdd`, method: 'POST'},
      updateBulkMenu: {url: `${this.baseUrl}/api/updateBulkMenu`, method: 'POST'},
      getCurrentBulkOrdersCount: {url: `${this.baseUrl}/api/getCurrentBulkOrdersCount`, method: 'GET'},
      getBulkOrderList: {url: `${this.baseUrl}/api/getBulkOrderList`, method: 'POST'},
      updateBulkFoodOrder: {url: `${this.baseUrl}/api/updateBulkFoodOrder`, method: 'POST'},
      changeFoodOrderAddress: {url: `${this.baseUrl}/api/changeFoodOrderAddress`, method: 'POST'},
      changeChildOrdersAddress: {url: `${this.baseUrl}/api/changeChildOrdersAddress`, method: 'POST'},
      changePackageStatus: {url: `${this.baseUrl}/api/changePackageStatus`, method: 'POST'},
      getCustomerFirstOrder: {url: `${this.baseUrl}/api/getCustomerFirstOrder`, method: 'POST'},
      createPidge3PLTask: {url: `${this.baseUrl}/api/createPidge3PLTask`, method: 'POST'},
      cancelPidge3PLOrder: {url: `${this.baseUrl}/api/cancelPidge3PLOrder`, method: 'PUT'},
      getAllMarketplaceItems: {url: `${this.baseUrl}/api/getAllMarketplaceItems`, method:'GET'},
      savemarketplaceItem: {url: `${this.baseUrl}/api/savemarketplaceItem`, method: 'POST'},
      updatemarketplaceItem: {url: `${this.baseUrl}/api/updatemarketplaceItem`, method: 'PATCH'},
      marketplaceItemAvailability: {url: `${this.baseUrl}/api/changemarketplaceAvailability`, method: 'PUT'},
      getDayRangeBasedLogs:{url:`${this.baseUrl}/utility/getDayRangeBasedLogs`,method:'GET'},
      getTimeBasedLogs:{url:`${this.baseUrl}/utility/getTimeBasedLogs`,method:'GET'},
      getLineBasedLogs:{url:`${this.baseUrl}/utility/getLineBasedLogs`,method:'GET'},
      getDayRangeBasedAuditLogs: {url: `${this.baseUrl}/utility/getDayRangeBasedAuditLogs`,method: 'GET'},
      getTimeBasedAuditLogs: {url: `${this.baseUrl}/utility/getTimeBasedAuditLogs`,method: 'GET'},
      getLineBasedAuditLogs: {url: `${this.baseUrl}/utility/getLineBasedAuditLogs`,method: 'GET'},
      getAllKitchenWalletList:{url:`${this.baseUrl}/api/getAllKitchenWalletList`,method:'GET'},
      getClusterCurrentOrdersCount: {url: `${this.baseUrl}/api/getClusterCurrentOrdersCount`, method: 'POST'},
      getClusterCurrentSubscriptionCount: {url: `${this.baseUrl}/api/getClusterCurrentSubscriptionCount`, method: 'POST'},
      getClusterCurrentBulkOrdersCount: {url: `${this.baseUrl}/api/getClusterCurrentBulkOrdersCount`, method: 'POST'},
      getClusterCurrentPackageCount: {url: `${this.baseUrl}/api/getClusterCurrentPackageCount`, method: 'POST'},
      getClusterCurrentOrdersList: {url: `${this.baseUrl}/api/getClusterCurrentOrdersList`, method: 'POST'},
      getClusterCurrentPackageOrdersList: {url: `${this.baseUrl}/api/getClusterCurrentPackageOrdersList`, method: 'POST'},
      getClusterBulkOrderList: {url: `${this.baseUrl}/api/getClusterBulkOrderList`, method: 'POST'},
      orderListToDeliver: {url: `${this.baseUrl}/api/orderListToDeliver`, method: 'POST'},
      marketPlaceGrouplist: {url: `${this.baseUrl}/api/marketPlaceGrouplist`, method: 'GET'},
      marketPlaceGroup: {url: `${this.baseUrl}/api/marketPlaceGroup`, method: 'POST'},
      updatemarketPlaceGroup: {url: `${this.baseUrl}/api/updatemarketPlaceGroup`, method: 'POST'},
      deletemarketPlaceGroup: {url: `${this.baseUrl}/api/deletemarketPlaceGroup`, method: 'DELETE'},
      checkUserWallet: {url: `${this.baseUrl}/api/checkUserWallet`, method: 'POST'},
      getAllMarketPlaceItem: {url: `${this.baseUrl}/api/getAllMarketPlaceItem`, method: 'GET'},
      getMarketPlaceItemById: {url: `${this.baseUrl}/api/getMarketPlaceItemById`, method: 'GET'},
      saveMarketPlaceItem: {url: `${this.baseUrl}/api/saveMarketPlaceItem`, method: 'POST'},
      updateMarketPlaceItem: {url: `${this.baseUrl}/api/updateMarketPlaceItem`, method: 'POST'},
      updateMarketPlaceItemImage: {url: `${this.baseUrl}/api/updateMarketPlaceItemImage`, method: 'POST'},
      deleteMarketPlaceItem: {url: `${this.baseUrl}/api/deleteMarketPlaceItem`, method: 'DELETE'},
      deleteMarketPlaceItemImage: {url: `${this.baseUrl}/api/deleteMarketPlaceItemImage`, method: 'DELETE'},
      saveMarketPlaceInventory: {url: `${this.baseUrl}/api/saveMarketPlaceInventory`, method: 'POST'},
      getMarketPlaceInventory: {url: `${this.baseUrl}/api/getMarketPlaceInventory`, method: 'GET'},
      getMarketPlaceInventoryById: {url: `${this.baseUrl}/api/getMarketPlaceInventoryById`, method: 'GET'},
      updateMarketPlaceInventory: {url: `${this.baseUrl}/api/updateMarketPlaceInventory`, method: 'POST'},
      deleteMarketPlaceInventory: {url: `${this.baseUrl}/api/deleteMarketPlaceInventory`, method: 'DELETE'},
      getMarketPlaceItemOrdersCount: {url: `${this.baseUrl}/api/getMarketPlaceItemOrdersCount`, method: 'GET'},
      getMarketPlaceItemOrdersList: {url: `${this.baseUrl}/api/getMarketPlaceItemOrdersList`, method: 'GET'},
      getMarketPlaceMainOrdersCount: {url: `${this.baseUrl}/api/getMarketPlaceMainOrdersCount`, method: 'GET'},
      getMarketPlaceMainOrdersList: {url: `${this.baseUrl}/api/getMarketPlaceMainOrdersList`, method: 'GET'},
      updateMarketPlaceMainAndItemOrder: {url: `${this.baseUrl}/api/updateMarketPlaceMainAndItemOrder`, method: 'POST'},
      getMarketPlaceInventoryByItemId: {url: `${this.baseUrl}/api/getMarketPlaceInventoryByItemId`, method: 'GET'},
      updateMarketPlaceItemOrder: {url: `${this.baseUrl}/api/updateMarketPlaceItemOrder`, method: 'POST'},
      updateMarketPlaceItemOrderStatus: {url: `${this.baseUrl}/api/updateMarketPlaceItemOrderStatus`, method: 'POST'},
      updateMarketPlaceMainAndItemOrderInfo: {url: `${this.baseUrl}/api/updateMarketPlaceMainAndItemOrderInfo`, method: 'POST'},
      updateAllItemOrdersInfo: {url: `${this.baseUrl}/api/updateAllItemOrdersInfo`, method: 'POST'},
      createShipRocketDeliveryTask: {url: `${this.baseUrl}/api/createShipRocketDeliveryTask`, method: 'POST'},
      cancelShipRocketDeliveryTask: {url: `${this.baseUrl}/api/cancelShipRocketDeliveryTask`, method: 'PUT'},
      trackShipRocketDeliveryTask: {url: `${this.baseUrl}/api/trackShipRocketDeliveryTask`, method: 'GET'},
      generateShipRocketMenifest: {url: `${this.baseUrl}/api/generateShipRocketMenifest`, method: 'GET'},
      generateShipRocketLabel: {url: `${this.baseUrl}/api/generateShipRocketLabel`, method: 'GET'},
      generateShipRocketInvoice: {url: `${this.baseUrl}/api/generateShipRocketInvoice`, method: 'GET'},
      getCombineOrderForDelivery: {url: `${this.baseUrl}/api/getCombineOrderForDelivery`, method: 'GET'},
      updateInventoryItemLimit: {url: `${this.baseUrl}/api/updateInventoryItemLimit`, method: 'POST'},
      getInventoryItemHistory: {url: `${this.baseUrl}/api/getInventoryItemHistory`, method: 'GET'},
      updateStandAloneShipment: {url: `${this.baseUrl}/api/updateStandAloneShipment`, method: 'POST'},
      cancelMarketPlaceItemOrder: {url: `${this.baseUrl}/api/cancelMarketPlaceItemOrder`, method: 'POST'},
      searchMarketPlaceItemOrderList: {url: `${this.baseUrl}/api/searchMarketPlaceItemOrderList`, method: 'POST'},
      searchMarketPlaceMainOrderList: {url: `${this.baseUrl}/api/searchMarketPlaceMainOrderList`, method: 'POST'},
      updateUserRMInfo: {url: `${this.baseUrl}/api/updateUserRMInfo`, method: 'POST'},
      assignRMtoUserOrder: {url: `${this.baseUrl}/api/assignRMtoUserOrder`, method: 'POST'},
      saveHotel: {url: `${this.baseUrl}/api/saveHotel`, method: 'POST'},
      getAllHotels: {url: `${this.baseUrl}/api/getAllHotels`, method: 'GET'},
      getAllKitchenPatners: {url: `${this.baseUrl}/api/getAllKitchenPatners`, method: 'GET'},
      getHotelByID: {url: `${this.baseUrl}/api/getHotelByID`, method: 'GET'},
      updateHotel: {url: `${this.baseUrl}/api/updateHotel`, method: 'PUT'},
      deleteHotel: {url: `${this.baseUrl}/api/deleteHotel`, method: 'DELETE'},
      getUtmEvents: {url: `${this.baseUrl}/api/utmEvents`, method: 'GET'},
      getCustomerMarketPlaceItemPastOrders: { url: `${this.baseUrl}/api/getCustomerMarketPlaceItemPastOrders`, method: 'GET', },
   };
  }
}
